export default defineEventHandler((event) => {
  const cars = [
    {
      city_mpg: 59,
      class: "Electric Pickup Truck",
      combination_mpg: 53,
      drive: "All-Wheel Drive",
      fuel_type: "Electric",
      make: "GMC",
      model: "Hummer EV Pickup",
      transmission: "Automatic",
      seat: 6,
      rental_price_per_day: "$150 - $200",
      availability: "Available",
      img: "https://www.gmc.com/content/dam/gmc/na/us/english/index/vehicles/future-vehicles/hummer/hub-page/my23-hummersuv-acc-full-1920x1080.jpg?imwidth=960",
    },
    {
      city_mpg: 14,
      class: "Luxury SUV",
      combination_mpg: 15,
      drive: "Four-Wheel Drive",
      fuel_type: "Gasoline",
      make: "GMC",
      model: "Hummer H2 SUV",
      transmission: "Automatic",
      seat: 6,
      rental_price_per_day: "$100 - $150",
      availability: "Limited",
      img: "https://c4.wallpaperflare.com/wallpaper/246/567/742/2009-hummer-h2-wallpaper-preview.jpg",
    },
    {
      city_mpg: 50,
      class: "Electric Pickup Truck",
      combination_mpg: 45,
      drive: "All-Wheel Drive",
      fuel_type: "Electric",
      make: "GMC",
      model: "Hummer EV Pickup",
      transmission: "Automatic",
      seat: 6,
      rental_price_per_day: "$130 - $180",
      availability: "Available",
      img: "https://di-uploads-pod25.dealerinspire.com/hendrickchevybuickgmcsouthpoint/uploads/2020/10/2020-gmc-hummer-ev-banner-image.png",
    },

    {
      city_mpg: 120,
      class: "Electric Sedan",
      combination_mpg: 118,
      drive: "All-Wheel Drive",
      fuel_type: "Electric",
      make: "Tesla",
      model: "Tesla Model 3 Standard Range Plus",
      transmission: "Automatic",
      seat: 5,
      rental_price_per_day: "$100 - $150",
      availability: "Available",
      img: "https://th.bing.com/th/id/OIP.eQfOg7GZPj1Smo_RTmUPYQHaFj?rs=1&pid=ImgDetMain",
    },
    {
      city_mpg: 134,
      class: "Electric Sedan",
      combination_mpg: 130,
      drive: "All-Wheel Drive",
      fuel_type: "Electric",
      make: "Tesla",
      model: "Tesla Model 3 Long Range",
      transmission: "Automatic",
      seat: 5,
      rental_price_per_day: "$130 - $180",
      availability: "Available",
      img: "https://ev-database.org/img/auto/Tesla_Model_3/Tesla_Model_3-01@2x.jpg",
    },
    {
      city_mpg: 113,
      class: "Electric Sedan",
      combination_mpg: 110,
      drive: "All-Wheel Drive",
      fuel_type: "Electric",
      make: "Tesla",
      model: "Tesla Model 3 Performance",
      transmission: "Automatic",
      seat: 5,
      rental_price_per_day: "$160 - $220",
      availability: "Limited",
      img: "https://manofmany.com/wp-content/uploads/2024/04/Tesla-Model-3-Performance-in-red.jpg",
    },
    {
      city_mpg: 16,
      class: "Luxury Sports Car",
      combination_mpg: 14,
      drive: "All-Wheel Drive",
      fuel_type: "Gasoline",
      make: "Ferrari",
      model: "Ferrari SF90 Stradale",
      transmission: "Automatic",
      seat: 2,
      rental_price_per_day: "$800 - $1200",
      availability: "Limited",
      img: "https://img.indianautosblog.com/2023/07/01/ferrari-sf90-xx-stradale-front-quarter-7340.jpg",
    },
    {
      city_mpg: 13,
      class: "Luxury Sports Car",
      combination_mpg: 11,
      drive: "Rear-Wheel Drive",
      fuel_type: "Gasoline",
      make: "Ferrari",
      model: "Ferrari 458 Spider",
      transmission: "Automatic",
      seat: 2,
      rental_price_per_day: "$700 - $1000",
      availability: "Available",
      img: "https://th.bing.com/th/id/R.5a59a9a789aa8caa9e041b4e4aa4aa8d?rik=XGLjGRbYUaEbWQ&riu=http%3a%2f%2fgtspirit.com%2fwp-content%2fuploads%2f2015%2f01%2fWhite-Ferrari-458-Spider-3.jpg&ehk=5f1J8WheJtZDJ9WsjxDnukgPTBcxJ6Ahfuy1TW%2fpGpQ%3d&risl=&pid=ImgRaw&r=0",
    },

    {
      city_mpg: 14,
      class: "Luxury Sports Car",
      combination_mpg: 12,
      drive: "Rear-Wheel Drive",
      fuel_type: "Gasoline",
      make: "Ferrari",
      model: "Ferrari F8 Tributo",
      transmission: "Automatic",
      seat: 2,
      rental_price_per_day: "$750 - $1100",
      availability: "Limited",
      img: "https://th.bing.com/th/id/OIP.07OitvH1Rfexh0lp00e98QHaFj?w=1920&h=1440&rs=1&pid=ImgDetMain",
    },
    {
      city_mpg: 18,
      class: "Luxury Sports Car",
      combination_mpg: 15,
      drive: "Rear-Wheel Drive",
      fuel_type: "Gasoline",
      make: "Porsche",
      model: "Porsche 911 Turbo S",
      transmission: "Automatic",
      seat: 2,
      rental_price_per_day: "$500 - $800",
      availability: "Available",
      img: "https://www.zero2turbo.com/wp-content/uploads/2020/10/2021-porsche-911-turbo-s-south-africa-zero2turbo-3-scaled.jpg",
    },
    {
      city_mpg: 16,
      class: "Luxury Sports Car",
      combination_mpg: 14,
      drive: "Rear-Wheel Drive",
      fuel_type: "Gasoline",
      make: "Porsche",
      model: "Porsche 718 Cayman GT4",
      transmission: "Manual",
      seat: 2,
      rental_price_per_day: "$400 - $700",
      availability: "Limited",
      img: "https://media.carsandbids.com/cdn-cgi/image/width=712,height=468,quality=70/d9b636c2ec84ddc3bc7f2eb32861b39bdd5f9683/photos/3zJaP7LJ.2iSAeKfYb-(edit).jpg?t=164469415724",
    },
    {
      city_mpg: 20,
      class: "Electric Sports Sedan",
      combination_mpg: 19,
      drive: "All-Wheel Drive",
      fuel_type: "Electric",
      make: "Porsche",
      model: "Porsche Taycan Turbo S",
      transmission: "Automatic",
      seat: 4,
      rental_price_per_day: "$600 - $1000",
      availability: "Available",
      img: "https://stat.overdrive.in/wp-content/odgallery/2019/09/53609_Porsche_Taycan_ev_005.jpg",
    },
    {
      city_mpg: 14,
      class: "Luxury Hypercar",
      combination_mpg: 12,
      drive: "Rear-Wheel Drive",
      fuel_type: "Gasoline",
      make: "McLaren",
      model: "McLaren Senna",
      transmission: "Automatic",
      seat: 2,
      rental_price_per_day: "$3,000 - $5,000",
      availability: "Limited",
      img: "https://i.pinimg.com/736x/2f/c3/39/2fc33930bf4aaabd057f90f90b7385bd.jpg",
    },
    {
      city_mpg: 15,
      class: "Luxury Sports Car",
      combination_mpg: 13,
      drive: "Rear-Wheel Drive",
      fuel_type: "Gasoline",
      make: "McLaren",
      model: "McLaren 720S",
      transmission: "Automatic",
      seat: 2,
      rental_price_per_day: "$900 - $1,500",
      availability: "Available",
      img: "https://i.redd.it/0wqs0m89b4nz.jpg",
    },
    {
      city_mpg: 16,
      class: "Luxury Supercar",
      combination_mpg: 14,
      drive: "Rear-Wheel Drive",
      fuel_type: "Gasoline",
      make: "McLaren",
      model: "McLaren Artura",
      transmission: "Automatic",
      seat: 2,
      rental_price_per_day: "$700 - $1,200",
      availability: "Available",
      img: "https://images.alphacoders.com/113/1131466.jpg",
    },
  ];

  // Log to verify the request query and handler
  console.log("API hit with query:", getQuery(event));

  const query = getQuery(event);

  if (query.model) {
    // Filter cars based on model
    const filteredCars = cars.filter((car) =>
      car.model.toLowerCase().includes(query.model.toLowerCase())
    );

    console.log("Filtered cars:", filteredCars); // Log filtered cars

    return filteredCars;
  }

  return cars;
});
